name: Labeler

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Label PR
        uses: actions/labeler@v4
        with:
          # Configuration file path
          config: .github/labeler.yml
